// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_oKidkIJ7po28QooxD4LBycmiKk75JAc',
    appId: '1:522195949252:web:59dec782b1e4bb0a62db91',
    messagingSenderId: '522195949252',
    projectId: 'mini-docto',
    authDomain: 'mini-docto.firebaseapp.com',
    storageBucket: 'mini-docto.firebasestorage.app',
    measurementId: 'G-Z2T8W7R47B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA34zXhOhKEa7uatvvBWSoCamCrTPq5LJs',
    appId: '1:522195949252:android:e8f30912db16c1d662db91',
    messagingSenderId: '522195949252',
    projectId: 'mini-docto',
    storageBucket: 'mini-docto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSuAqE_ShgkDin9-Kx8eYe1nFKHN-NCmo',
    appId: '1:522195949252:ios:7658cdb7fb0e330762db91',
    messagingSenderId: '522195949252',
    projectId: 'mini-docto',
    storageBucket: 'mini-docto.firebasestorage.app',
    iosBundleId: 'com.example.flutterUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSuAqE_ShgkDin9-Kx8eYe1nFKHN-NCmo',
    appId: '1:522195949252:ios:7658cdb7fb0e330762db91',
    messagingSenderId: '522195949252',
    projectId: 'mini-docto',
    storageBucket: 'mini-docto.firebasestorage.app',
    iosBundleId: 'com.example.flutterUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_oKidkIJ7po28QooxD4LBycmiKk75JAc',
    appId: '1:522195949252:web:5c170a9d0ffce8e062db91',
    messagingSenderId: '522195949252',
    projectId: 'mini-docto',
    authDomain: 'mini-docto.firebaseapp.com',
    storageBucket: 'mini-docto.firebasestorage.app',
    measurementId: 'G-JK98LLF84D',
  );
}
